workflows:
  android-workflow:
    name: Android Release
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: eu.neostream.neo_stream
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - stream2free.pecorio@gmail.com

  ios-workflow:
    name: iOS Development
    environment:
      flutter: stable
      ios_signing:
        distribution_type: development
        bundle_identifier: eu.neostream.neoStream
        team_id: PERSONAL_TEAM
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Set up code signing
        script: |
          xcode-project use-profiles \
            --project ios/Runner.xcodeproj
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - stream2free.pecorio@gmail.com