name: neo_stream
description: "Neo-Stream - Application de streaming premium"
publish_to: 'none'
version: 1.3.1+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # UI Components
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # Video Player - video_player (Google ExoPlayer for Android TV) & media_kit (Windows Desktop)
  video_player: ^2.9.2
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  
  # Networking
  http: ^1.2.0
  
  # State Management
  provider: ^6.1.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  
  path_provider: ^2.1.0

  # Utils
  intl: ^0.19.0
  flutter_inappwebview: ^6.1.5
  flutter_animate: ^4.5.2
  wakelock_plus: ^1.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#050508"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/no_poster.png
    - assets/logo.png
    - assets/images/
